### PR TITLE
fix: change used range indices to bytes instead of chars

### LINKED ISSUE #79: Non ascii text breaks did_change endpoint 😊
HTR: type some non ascii char like 😊 into the editor

what happens: the document desyncs and diagnostics break
what should happen: everything should work as normal

This is most likely a problem with the differences between bythe and char indices in the did_change endpoint.

### PR DESCRIPTION
**Pull request by janekx21**
closes #79

### CODE REVIEW

**Comment by b-gehrke** [comment]
Re #82:
When formatting a document with Syntax Errors the lines containing errors are deleted. I would expect either formatting to abort entirely or to keep the lines affected lines unformatted (if possible)

File: crates/owl-ms-language-server/src/workspace.rs [hunk 1]
```diff
@@ -2370,17 +1493,19 @@ pub fn gen_diagnostics(node: &Node) -> Vec<Diagnostic> {
...
+                    // Diagnostic {
+                    // range: range.into_lsp(doc),
+                    // severity: Some(DiagnosticSeverity::ERROR),
+                    // code: None,
+                    // code_description: None,
+                    // source: Some("owl language server".to_string()),
+                    // message: msg.to_string(),
+                    // related_information: None,
+                    // tags: None,
+                    // data: None,
```
Comment (b-gehrke) [inline crates/owl-ms-language-server/src/workspace.rs:1507]: Dead code

**Comment by janekx21** [comment]
> Re #82: When formatting a document with Syntax Errors the lines containing errors are deleted. I would expect either formatting to abort entirely or to keep the lines affected lines unformatted (if possible)

Ahh thanks for catching this. It was because the happy path does ignore ERROR nodes in the syntax tree, when generating the formatted document. Therefore they where missing. I added a condition to not format nodes that have direct children that are ERROR nodes. As a consequence top level ERROR nodes stop the formatting of the whole document, but they are severe enough.
